# Generated by Django 6.0.3 on 2026-03-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courseapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Instructor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Learner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="course",
            name="instructors",
            field=models.ManyToManyField(blank=True, to="courseapp.instructor"),
        ),
        migrations.AddField(
            model_name="course",
            name="learners",
            field=models.ManyToManyField(blank=True, to="courseapp.learner"),
        ),
    ]
